### PR TITLE
Fix an issue where the timer would not work if [] was present

### LINKED ISSUE #15: Timer is not working
**Describe the bug**

```md
- [ ] [a] xxx
  - [ ] [(25m✍️ 5m☕️)1] xxx
```

**Your Environment**
- Package Version: v0.7.0

### PR DESCRIPTION
**Pull request by seachicken**
Fixes #15

### CODE REVIEW

File: src/pomodoro-edit-core.js [hunk 1]
```diff
@@ -118,11 +118,13 @@ export default class Core {
       if (found) {
         const syntax = found[2];
         if (syntax.trim().length === 0) {
+          lineNumber++;
```
Comment (seachicken) [inline src/pomodoro-edit-core.js:121]: Fix the problem of shifting line numbers as well.
